In [1]:
import numpy as np

In [2]:
image = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20],
    [21,22,23,24,25]
],dtype = float )
print ("original image;")
print (image)

original image;
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25.]]


In [3]:
normalized_image = image/255.0

print(" Normalized image:")
print (normalized_image)


 Normalized image:
[[0.00392157 0.00784314 0.01176471 0.01568627 0.01960784]
 [0.02352941 0.02745098 0.03137255 0.03529412 0.03921569]
 [0.04313725 0.04705882 0.05098039 0.05490196 0.05882353]
 [0.0627451  0.06666667 0.07058824 0.0745098  0.07843137]
 [0.08235294 0.08627451 0.09019608 0.09411765 0.09803922]]


In [4]:
flattened_image = normalized_image.flatten()

print (" Flattened image:")
print ( flattened_image)

 Flattened image:
[0.00392157 0.00784314 0.01176471 0.01568627 0.01960784 0.02352941
 0.02745098 0.03137255 0.03529412 0.03921569 0.04313725 0.04705882
 0.05098039 0.05490196 0.05882353 0.0627451  0.06666667 0.07058824
 0.0745098  0.07843137 0.08235294 0.08627451 0.09019608 0.09411765
 0.09803922]


In [5]:
weights1 = np.array([
    [0.1,0.2,0.3,0.4,0.5],
    [0.2,0.3,0.4,0.5,0.6],
    [0.3,0.4,0.5,0.6,0.7],
    [0.4,0.5,0.6,0.7,0.8],
    [0.5,0.6,0.7,0.8,0.9],
    [0.5,0.4,0.3,0.2,0.1],
    [0.6,0.5,0.4,0.3,0.2],
    [0.1,0.2,0.3,0.4,0.5],
    [0.2,0.3,0.4,0.5,0.6],
    [0.3,0.4,0.5,0.6,0.7],
    [0.4,0.5,0.6,0.7,0.8],
    [0.5,0.6,0.7,0.8,0.9],
    [0.5,0.4,0.3,0.2,0.1],
    [0.6,0.5,0.4,0.3,0.2],
    [0.1,0.2,0.3,0.4,0.5],
    [0.2,0.3,0.4,0.5,0.6],
    [0.3,0.4,0.5,0.6,0.7],
    [0.4,0.5,0.6,0.7,0.8],
    [0.5,0.6,0.7,0.8,0.9],
    [0.5,0.4,0.3,0.2,0.1],
    [0.6,0.5,0.4,0.3,0.2],
    [0.1,0.2,0.3,0.4,0.5],
    [0.2,0.3,0.4,0.5,0.6],
    [0.3,0.4,0.5,0.6,0.7],
    [0.4,0.5,0.6,0.7,0.8],

])
bias1 = np.array([0.1,0.2,0.3,0.4,0.5])

In [6]:
print ("weight shape:", weights1.shape)
print ("bias shape:", bias1.shape)

weight shape: (25, 5)
bias shape: (5,)


In [7]:
z1 = np.dot (flattened_image,weights1) + bias1
print("Output before ReLU:")
print (z1)

Output before ReLU:
[0.55764706 0.72156863 0.8854902  1.04941176 1.21333333]


In [8]:
def relu(x):
    return np.maximum(0,x)
    a1 = relu (z1)

In [9]:
z1 = np.dot (flattened_image, weights1,) + bias1
a1 = relu (z1)
print("Output after ReLU:")
print (z1)

Output after ReLU:
[0.55764706 0.72156863 0.8854902  1.04941176 1.21333333]


In [10]:
weights2 = np.array([
    [0.1,0.2,0.3,0.4,0.5],
    [0.2,0.3,0.4,0.5,0.6],
    [0.3,0.4,0.5,0.6,0.7],
    [0.4,0.5,0.6,0.7,0.8],
    [0.5,0.6,0.7,0.8,0.9],
])
bias2 = np.array([0.5,0.4,0.3,0.2,0.1])
z2 = np.dot (a1, weights2,) + bias2
a2 = relu (z2)

print(z2)

[1.99215686 2.33490196 2.67764706 3.02039216 3.36313725]


In [11]:
weights3 = np.array([
    [0.1,0.2,0.3,0.4,0.5],
    [0.4,0.5,0.6,0.7,0.8],
    [0.5,0.6,0.7,0.8,0.9],
    [0.2,0.3,0.4,0.5,0.6],
    [0.3,0.4,0.5,0.6,0.7], 
])
    
bias3 = np.array([0.4,0.3,0.5,0.2,0.1])
z3 = np.dot (a2, weights3,) + bias3
a3 = relu (z3)
print (z3)

[4.48501961 5.72384314 7.26266667 8.3014902  9.54031373]


In [12]:
weights4 = np.array([
    [0.1,0.2,0.3,0.4,0.5],
    [0.4,0.5,0.6,0.7,0.8],
    [0.5,0.6,0.7,0.8,0.9],
    [0.2,0.3,0.4,0.5,0.6],
    [0.5,0.6,0.7,0.8,0.9], 
])
    
bias4 = np.array([0.2,0.3,0.4,0.1,0.5])
z4 = np.dot (a3, weights4,) + bias4
print (z4)

[12.99982745 16.63116078 20.26249412 23.49382745 27.42516078]


In [13]:
for i in range (5):
    z1 = np.dot (flattened_image, weights1) + bias1
    a1 = relu(z1)
    
    z2 = np.dot (a1,weights2) + bias2
    a2 = relu(z2)
    
    z3 = np.dot (a2,weights3) + bias3
    a3 = relu(z3)
    
    z4 = np.dot (a3,weights4) + bias4
    output = (z4)
    
    print (f"iteration {i+1}:")
    print (output) 

iteration 1:
[12.99982745 16.63116078 20.26249412 23.49382745 27.42516078]
iteration 2:
[12.99982745 16.63116078 20.26249412 23.49382745 27.42516078]
iteration 3:
[12.99982745 16.63116078 20.26249412 23.49382745 27.42516078]
iteration 4:
[12.99982745 16.63116078 20.26249412 23.49382745 27.42516078]
iteration 5:
[12.99982745 16.63116078 20.26249412 23.49382745 27.42516078]
