In [2]:
import numpy as np

In [35]:
image = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
],dtype = float)

print("Original Image:")
print(image)

Original Image:
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25.]]


In [36]:
# Normalize the image
normalized_image = image / 255.0

print("Normalized Image:")
print(normalized_image)

Normalized Image:
[[0.00392157 0.00784314 0.01176471 0.01568627 0.01960784]
 [0.02352941 0.02745098 0.03137255 0.03529412 0.03921569]
 [0.04313725 0.04705882 0.05098039 0.05490196 0.05882353]
 [0.0627451  0.06666667 0.07058824 0.0745098  0.07843137]
 [0.08235294 0.08627451 0.09019608 0.09411765 0.09803922]]


In [37]:
# Flatten the normalized image
flattened_image = normalized_image.flatten()

print("Flattened Image:")
print(flattened_image)

print("\nShape:", flattened_image.shape)

Flattened Image:
[0.00392157 0.00784314 0.01176471 0.01568627 0.01960784 0.02352941
 0.02745098 0.03137255 0.03529412 0.03921569 0.04313725 0.04705882
 0.05098039 0.05490196 0.05882353 0.0627451  0.06666667 0.07058824
 0.0745098  0.07843137 0.08235294 0.08627451 0.09019608 0.09411765
 0.09803922]

Shape: (25,)


In [27]:
# Create weights for Hidden Layer 1
weights1 = np.random.randn(25, 5)

# Create bias for Hidden Layer 1
bias1 = np.random.randn(5)

print("Weights Shape:", weights1.shape)
print("Bias Shape:", bias1.shape)

Weights Shape: (25, 5)
Bias Shape: (5,)


In [39]:
# forward propagation
z1 = np.dot(flattened_image, weights1) + bias1

print("Output before ReLU:")
print(z1)

Output before ReLU:
[-1.52555694  0.58825942  0.74244317  0.032297   -0.38734903]


In [40]:
def relu(x):
    return np.maximum(0, x)

In [41]:
a1 = relu(z1)

print("Output after ReLU:")
print(a1)

Output after ReLU:
[0.         0.58825942 0.74244317 0.032297   0.        ]


In [42]:
weights2 = np.random.randn(5, 5)
bias2 = np.random.randn(5)
z2 = np.dot(a1, weights2) + bias2
a2 = relu(z2)

In [43]:
weights3 = np.random.randn(5, 5)
bias3 = np.random.randn(5)

z3 = np.dot(a2, weights3) + bias3
a3 = relu(z3)

In [44]:
weights4 = np.random.randn(5, 5)
bias4 = np.random.randn(5)

z4 = np.dot(a3, weights4) + bias4

In [45]:
for i in range(5):
    z1 = np.dot(flattened_image, weights1) + bias1
    a1 = relu(z1)

    z2 = np.dot(a1, weights2) + bias2
    a2 = relu(z2)

    z3 = np.dot(a2, weights3) + bias3
    a3 = relu(z3)

    z4 = np.dot(a3, weights4) + bias4
    output = softmax(z4)

    print(f"Iteration {i+1}:")
    print(output)

Iteration 1:
[0.71573312 0.00296878 0.00501814 0.26194465 0.01433531]
Iteration 2:
[0.71573312 0.00296878 0.00501814 0.26194465 0.01433531]
Iteration 3:
[0.71573312 0.00296878 0.00501814 0.26194465 0.01433531]
Iteration 4:
[0.71573312 0.00296878 0.00501814 0.26194465 0.01433531]
Iteration 5:
[0.71573312 0.00296878 0.00501814 0.26194465 0.01433531]


In [46]:
np.random.randn(25, 5)

array([[ 0.03866976,  0.54345428, -0.98703474,  0.3544412 ,  0.23083537],
       [-0.0929659 , -0.6689797 , -0.25894842, -0.71585855,  1.92553436],
       [ 3.50789577,  0.16113116, -1.83830046, -0.36859541, -1.38792458],
       [-1.5214296 , -0.31618345, -0.14365004, -0.19373526,  0.66175868],
       [-0.16900732,  0.77925827, -1.92288375, -0.25526213, -0.07319198],
       [ 1.62848322,  0.45178626,  2.37125759, -1.36639691, -1.10344417],
       [-1.98323528,  0.32986101, -0.3438486 ,  1.04179965, -0.17341224],
       [ 0.33358476, -1.48071952,  0.16508357,  1.16022896, -2.21443347],
       [-0.03353684, -0.21333422,  0.5720493 , -0.95986945,  1.60108593],
       [ 0.44519227,  0.61790088,  1.07550497,  0.87401891,  0.48747613],
       [-0.22673426,  0.24885338, -0.72115685,  1.75517687, -0.61232903],
       [-1.19024712, -0.7511935 , -2.08254681,  0.90618487,  0.23993016],
       [-1.60370581,  0.92655334, -0.16684084,  0.79948545,  1.01962964],
       [-1.3735652 ,  0.73959247, -0.7

In [47]:
np.random.randn(5)

array([ 0.17858984, -1.97654544,  1.37794392,  0.64772585,  0.07087573])